allow-uncaught: true
# bail: true
diff: true
extension:
  - js
recursive: true
reporter: spec
require: "@nomiclabs/buidler/register"
slow: 600
spec: test/**/test*.js # the positional arguments!
timeout: 0
ui: bdd
watch: false
watch-files:
  - "src/**/*.sol"
  - "test/**/*.js"
