site_name: The Sandbox Game
site_url: https://the-sandbox-game.readthedocs.io
theme:
  name: material
  features:
    - navigation.indexes
nav:
  - Getting started:
      - Install: intro/index.md
      - Running the tests: intro/running-tests.md
      - Setting environment variables: intro/setting-environment-variables.md
  - How to:
      - Fixing tests: howto/fixing-tests.md
      - Preparing a LAND sale: howto/preparing-land-sale.md
      - Preparing an ASSET giveaway: howto/preparing-asset-giveaway.md
      - Generating liquidity pool rewards: howto/generating-liquidity-pool-rewards.md
      - Running a lottery: howto/running-lottery.md
  - Tutorials:
      - Developing your first feature: tutorials/developing-first-feature.md
      - Writing documentation: tutorials/writing-documentation.md
  - Topics:
      - Blockchain:
          - Ethereum: topics/blockchain/ethereum.md
          - Features: topics/blockchain/features.md

markdown_extensions:
  - admonition
  - pymdownx.superfences
  - toc:
      permalink: '#'
  - plantuml_markdown:
      server: http://www.plantuml.com/plantuml
