site_name: The Sandbox Game
theme:
  name: material
nav:
  - Getting started:
    - Install: intro/index.md
    - Running the tests: intro/running-tests.md
  - How to:
    - Writing documentation: howto/writing-documentation.md
    - Fixing tests: howto/fixing-tests.md

markdown_extensions:
  - admonition
  - pymdownx.superfences
  - toc:
      permalink: "#"
