site_name: The Sandbox Game
theme:
  name: material
  features:
    - navigation.indexes
nav:
  - Getting started:
    - Install: intro/index.md
    - Running the tests: intro/running-tests.md
    - Setting environment variables: intro/setting-environment-variables.md
  - How to:
    - Fixing tests: howto/fixing-tests.md
    - Preparing a LAND sale: howto/preparing-land-sale.md
    - Claiming an asset: howto/claiming-asset.md
  - Tutorials:
    - Developing your first feature: tutorials/developing-first-feature.md
  - Topics:
    - Blockchain:
      - Ethereum: topics/blockchain/ethereum.md
      - Features: topics/blockchain/features.md
    - Architecture: topics/architecture/index.md

markdown_extensions:
  - admonition
  - pymdownx.superfences
  - toc:
      permalink: "#"
